# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('afeganistao', 'Afeganistão'), ('africa_do_sul', 'África do Sul'), ('albania', 'Albânia'), ('alemanha', 'Alemanha'), ('andorra', 'Andorra'), ('angola', 'Angola'), ('antiga_barbuda', 'Antiga e Barbuda'), ('arabia', 'Arábia Saudita'), ('argelia', 'Argélia'), ('argentina', 'Argentina'), ('arménia', 'Arménia'), ('australia', 'Austrália'), ('austria', 'Áustria'), ('azer', 'Azerbaijão'), ('angola', 'Bahamas'), ('bangladexe', 'Bangladexe'), ('barbados', 'Barbados'), ('barem', 'Barém'), ('belgica', 'Bélgica'), ('belize', 'Belize'), ('benim', 'Benim'), ('bielorrussia', 'Bielorrússia'), ('bolivia', 'Bolívia'), ('bosnia', 'Bósnia e Herzegovina'), ('botsuana', 'Botsuana'), ('brasil', 'Brasil'), ('brunei', 'Brunei'), ('bulgaria', 'Bulgária'), ('burquina', 'Burquina Faso'), ('burundi', 'Burúndi'), ('butao', 'Butão'), ('cabo_verde', 'Cabo Verde'), ('camaraes', 'Camarões'), ('camboja', 'Camboja'), ('canada', 'Canadá'), ('catar', 'Catar'), ('cazaquistao', 'Cazaquistão'), ('chade', 'Chade'), ('chile', 'Chile'), ('china', 'China'), ('chipre', 'Chipre'), ('colombia', 'Colômbia'), ('comores', 'Comores'), ('congo', 'Congo-Brazzaville'), ('coreia_norte', 'Coreia do Norte'), ('coreia_sul', 'Coreia do Sul'), ('cosvo', 'Cosovo'), ('costa_marfim', 'Costa do Marfim'), ('costa_rica', 'Costa Rica'), ('croacia', 'Croácia'), ('cuaite', 'Cuaite'), ('cuba', 'Cuba'), ('dinamarca', 'Dinamarca'), ('dominca', 'Dominica'), ('egito', 'Egito'), ('emirados', 'Emirados Árabes Unidos'), ('equador', 'Equador'), ('eritreia', 'Eritreia'), ('eslovaquia', 'Eslováquia'), ('eslovenia', 'Eslovénia'), ('espanha', 'Espanha'), ('palestina', 'Estado da Palestina'), ('eua', 'Estados Unidos'), ('estonia', 'Estónia'), ('etiopia', 'Etiópia'), ('fiji', 'Fiji'), ('filipinas', 'Filipinas'), ('finlandia', 'Finlândia'), ('franca', 'França'), ('gabao', 'Gabão'), ('gambia', 'Gâmbia'), ('gana', 'Gana'), ('georgia', 'Geórgia'), ('granada', 'Granada'), ('grecia', 'Grécia'), ('guine_e', 'Guiné Equatorial'), ('guine_b', 'Guiné-Bissau'), ('haiti', 'Haiti'), ('honduras', 'Honduras'), ('hungria', 'Hungria'), ('iemen', 'Iémen'), ('ilhas', 'Ilhas Marechal'), ('india', 'Índia'), ('indonésia', 'Indonésia'), ('irao', 'Irão'), ('iraque', 'Iraque'), ('irlanda', 'Irlanda'), ('islandia', 'Islândia'), ('israel', 'Israel'), ('italia', 'Itália'), ('jamaica', 'Jamaica'), ('japao', 'Japão'), ('jibuti', 'Jibuti'), ('jordania', 'Jordânia'), ('laus', 'Laus'), ('lesoto', 'Lesoto'), ('letonia', 'Letónia'), ('libano', 'Líbano'), ('liberia', 'Libéria'), ('libia', 'Líbia'), ('listenstaine', 'Listenstaine'), ('lituania', 'Lituânia'), ('luxemburgo', 'Luxemburgo'), ('macedonia', 'Macedónia'), ('madagascar', 'Madagáscar'), ('malasia', 'Malásia'), ('malaui', 'Maláui'), ('maldivas', 'Maldivas'), ('mali', 'Mali'), ('malta', 'Malta'), ('marrocos', 'Marrocos'), ('mauricia', 'Maurícia'), ('mauritania', 'Mauritânia'), ('mexico', 'México'), ('mianmar', 'Mianmar'), ('micronesia', 'Micronésia'), ('mocambique', 'Moçambique'), ('moldavia', 'Moldávia'), ('monaco', 'Mónaco'), ('mongolia', 'Mongólia'), ('montenegro', 'Montenegro'), ('namibia', 'Namíbia'), ('nauru', 'Nauru'), ('nepal', 'Nepal'), ('nicaragua', 'Nicarágua'), ('niger', 'Níger'), ('nigeria', 'Nigéria'), ('noruega', 'Noruega'), ('nova_zelandia', 'Nova Zelândia'), ('oma', 'Omã'), ('paises_baixos', 'Países Baixos'), ('palau', 'Palau'), ('panama', 'Panamá'), ('nova_guine', 'Papua Nova Guiné'), ('paquistao', 'Paquistão'), ('paraguai', 'Paraguai'), ('peru', 'Peru'), ('polonia', 'Polónia'), ('portugal', 'Portugal'), ('quenia', 'Quénia'), ('quirguistao', 'Quirguistão'), ('quiribati', 'Quiribáti'), ('reino_unido', 'Reino Unido'), ('republica_ca', 'República Centro-Africana'), ('republica_checa', 'República Checa'), ('republica_dc', 'República Democrática do Congo'), ('republica_d', 'República Dominicana'), ('romenia', 'Roménia'), ('ruanda', 'Ruanda'), ('russia', 'Rússia'), ('salomao', 'Salomão'), ('salvador', 'Salvador'), ('samoa', 'Samoa'), ('santa_lucia', 'Santa Lúcia'), ('sao_cristovao', 'São Cristóvão e Neves'), ('sao_marinho', 'São Marinho'), ('sao_tome', 'São Tomé e Príncipe'), ('sao_vicente', 'São Vicente e Granadinas'), ('seicheles', 'Seicheles'), ('senegal', 'Senegal'), ('serra', 'Serra Leoa'), ('servia', 'Sérvia'), ('singapura', 'Singapura'), ('siria', 'Síria'), ('angola', 'Somália'), ('sri_Lanca', 'Sri Lanca'), ('suazilandia', 'Suazilândia'), ('sudao', 'Sudão'), ('sudao_sul', 'Sudão do Sul'), ('suecia', 'Suécia'), ('suica', 'Suíça'), ('suriname', 'Suriname'), ('tailandia', 'Tailândia'), ('taiua', 'Taiuã'), ('tajiquistao', 'Tajiquistão'), ('tanzania', 'Tanzânia'), ('timor_leste', 'Timor-Leste'), ('togo', 'Togo'), ('tonga', 'Tonga'), ('trindade_tobago', 'Trindade e Tobago'), ('tunisia', 'Tunísia'), ('turcomenistao', 'Turcomenistão'), ('turquia', 'Turquia'), ('tuvalu', 'Tuvalu'), ('ucrania', 'Ucrânia'), ('uganda', 'Uganda'), ('uruguai', 'Uruguai'), ('usbequistao', 'Usbequistão'), ('vanuatu', 'Vanuatu'), ('vaticano', 'Vaticano'), ('venezuela', 'Venezuela'), ('vietname', 'Vietname'), ('zambia', 'Zâmbia'), ('zimbabue', 'Zimbábue')], max_length=50, verbose_name='País')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('modalidade', models.CharField(max_length=50, verbose_name='Modalidade')),
                ('vigencia', models.DateField(verbose_name='Vigência')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('area_pesquisa', models.CharField(max_length=50, verbose_name='Área de Pesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='bolsa',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Instituicao', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='pesquisador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pesquisador', verbose_name='Pesquisador'),
        ),
        migrations.AddField(
            model_name='bolsa',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Programa', verbose_name='Programa'),
        ),
    ]
